import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import type { QuestBossIndex } from '@/lib/types'

/**
 * Which bosses appear in a given quest — the inverse of each boss's
 * `questAppearances`, generated by `build-bosses`.
 *
 * **A separate 2.8 KB file, deliberately.** Quest detail is the only consumer,
 * and deriving this in the app would mean loading the 91 KB boss dataset there
 * to render at most a handful of links. Only 20 of 214 quests have an entry at
 * all, so most opens read an empty map and show nothing.
 *
 * Nothing is persisted: generated, read-only, ships with the build.
 */
export const useQuestBossesStore = defineStore('questBosses', () => {
  const index = ref<QuestBossIndex | null>(null)
  const loading = ref(false)

  async function ensureIndex(): Promise<void> {
    if (index.value || loading.value) return
    loading.value = true
    try {
      const module = await import('@/data/quest-bosses.json')
      index.value = module.default as unknown as QuestBossIndex
    } finally {
      loading.value = false
    }
  }

  /** The bosses appearing in one quest, or an empty list. */
  const forQuest = computed(
    () =>
      (questId: string): { id: string; name: string }[] =>
        index.value?.byQuest[questId] ?? [],
  )

  return { index, loading, forQuest, ensureIndex }
})
